### ISSUE TITLE
Wrong determination of the death position of the monster

### ISSUE THREAD

**Issue by martin-zyb** [bridgeL/pacman2#1]
### Problem
When a monster is eaten by a Pac Man, if it is not at an integer node position on a finite orbit, it may get stuck and become unresponsive

**Comment by bridgeL** [comment]
I'm extremely happy that you find here (_it's a 3-year-old project!_) and post your issue. However, I'm busy in struggling in my life nowadays and I haven't write c++ project for years. I'm afraid that I cannot fix this bug in the near future. Sorry for that. Or you can fix this bug and pull requests to this repo.

**Comment by martin-zyb** [comment]
> I'm extremely happy that you find here (_it's a 3-year-old project!_) and post your issue. However, I'm busy in struggling in my life nowadays and I haven't write c++ project for years. I'm afraid that I cannot fix this bug in the near future. Sorry for that. Or you can fix this bug and pull requests to this repo.

There is already a PR (#2)
